Fix: `util.deprecate` error in `speakeasy`
The error `Uncaught TypeError: util.deprecate is not a function` is caused by the `speakeasy` library. This commit will address the issue.